// <auto-generated />
using System;
using API.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(VeterinarianDB))]
    [Migration("20231217173708_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalId"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeAnimalId")
                        .HasColumnType("int");

                    b.Property<string>("URLImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TypeAnimalId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("API.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateToMeet")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InscriptionId")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId");

                    b.HasIndex("AnimalId");

                    b.HasIndex("InscriptionId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("API.Models.Canton", b =>
                {
                    b.Property<int>("CantonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CantonId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("CantonId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Cantons");

                    b.HasData(
                        new
                        {
                            CantonId = 1,
                            Name = "San José",
                            ProvinceId = 1
                        },
                        new
                        {
                            CantonId = 2,
                            Name = "San Pedro",
                            ProvinceId = 1
                        },
                        new
                        {
                            CantonId = 3,
                            Name = "Alajuela",
                            ProvinceId = 2
                        },
                        new
                        {
                            CantonId = 4,
                            Name = "Grecia",
                            ProvinceId = 2
                        },
                        new
                        {
                            CantonId = 5,
                            Name = "Cartago",
                            ProvinceId = 3
                        },
                        new
                        {
                            CantonId = 6,
                            Name = "Paraíso",
                            ProvinceId = 3
                        },
                        new
                        {
                            CantonId = 7,
                            Name = "Santo Domingo",
                            ProvinceId = 4
                        },
                        new
                        {
                            CantonId = 8,
                            Name = "San Pablo",
                            ProvinceId = 4
                        },
                        new
                        {
                            CantonId = 9,
                            Name = "Puntarenas",
                            ProvinceId = 5
                        },
                        new
                        {
                            CantonId = 10,
                            Name = "Quepos",
                            ProvinceId = 5
                        },
                        new
                        {
                            CantonId = 11,
                            Name = "Limón",
                            ProvinceId = 6
                        },
                        new
                        {
                            CantonId = 12,
                            Name = "Guapiles",
                            ProvinceId = 6
                        },
                        new
                        {
                            CantonId = 13,
                            Name = "Guanacaste",
                            ProvinceId = 7
                        },
                        new
                        {
                            CantonId = 14,
                            Name = "Nicoya",
                            ProvinceId = 7
                        });
                });

            modelBuilder.Entity("API.Models.Clinic", b =>
                {
                    b.Property<int>("ClinicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClinicId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("URLLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClinicId");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentificationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("SecondLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SexId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.HasIndex("SexId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            DNI = 11111,
                            Email = "sample@mail.com",
                            HashPassword = "default",
                            IdentificationType = "National",
                            LastName = "Prueba",
                            Name = "nombre",
                            PhoneNumber = 888888,
                            SecondLastName = "prueba",
                            SexId = 1,
                            UserName = "default"
                        });
                });

            modelBuilder.Entity("API.Models.Diagnostic", b =>
                {
                    b.Property<int>("DiagnosticId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiagnosticId"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InscriptionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiagnosticId");

                    b.HasIndex("AnimalId");

                    b.HasIndex("InscriptionId");

                    b.ToTable("Diagnostics");
                });

            modelBuilder.Entity("API.Models.Direction", b =>
                {
                    b.Property<int>("DirectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DirectionId"));

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DirectionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("DirectionId");

                    b.HasIndex("ClinicId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DistrictId");

                    b.ToTable("Directions");
                });

            modelBuilder.Entity("API.Models.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistrictId"));

                    b.Property<int>("CantonId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DistrictId");

                    b.HasIndex("CantonId");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            DistrictId = 1,
                            CantonId = 1,
                            Name = "San Miguel"
                        },
                        new
                        {
                            DistrictId = 2,
                            CantonId = 1,
                            Name = "Escazú"
                        },
                        new
                        {
                            DistrictId = 3,
                            CantonId = 2,
                            Name = "San Pedro"
                        },
                        new
                        {
                            DistrictId = 4,
                            CantonId = 2,
                            Name = "San Rafael"
                        },
                        new
                        {
                            DistrictId = 5,
                            CantonId = 3,
                            Name = "Alajuela"
                        },
                        new
                        {
                            DistrictId = 6,
                            CantonId = 3,
                            Name = "San Ramón"
                        },
                        new
                        {
                            DistrictId = 7,
                            CantonId = 4,
                            Name = "Grecia"
                        },
                        new
                        {
                            DistrictId = 8,
                            CantonId = 4,
                            Name = "Sarchí"
                        },
                        new
                        {
                            DistrictId = 9,
                            CantonId = 5,
                            Name = "Cartago"
                        },
                        new
                        {
                            DistrictId = 10,
                            CantonId = 5,
                            Name = "Paraíso"
                        },
                        new
                        {
                            DistrictId = 11,
                            CantonId = 6,
                            Name = "Santo Domingo"
                        },
                        new
                        {
                            DistrictId = 12,
                            CantonId = 6,
                            Name = "San Vicente"
                        },
                        new
                        {
                            DistrictId = 13,
                            CantonId = 7,
                            Name = "Santo Domingo"
                        },
                        new
                        {
                            DistrictId = 14,
                            CantonId = 7,
                            Name = "San Juanillo"
                        },
                        new
                        {
                            DistrictId = 15,
                            CantonId = 8,
                            Name = "San Pablo"
                        },
                        new
                        {
                            DistrictId = 16,
                            CantonId = 8,
                            Name = "San Isidro"
                        },
                        new
                        {
                            DistrictId = 17,
                            CantonId = 9,
                            Name = "Puntarenas"
                        },
                        new
                        {
                            DistrictId = 18,
                            CantonId = 9,
                            Name = "Chacarita"
                        },
                        new
                        {
                            DistrictId = 19,
                            CantonId = 10,
                            Name = "Quepos"
                        },
                        new
                        {
                            DistrictId = 20,
                            CantonId = 10,
                            Name = "Parrita"
                        },
                        new
                        {
                            DistrictId = 21,
                            CantonId = 11,
                            Name = "Limón"
                        },
                        new
                        {
                            DistrictId = 22,
                            CantonId = 11,
                            Name = "Guácimo"
                        },
                        new
                        {
                            DistrictId = 23,
                            CantonId = 12,
                            Name = "Guápiles"
                        },
                        new
                        {
                            DistrictId = 24,
                            CantonId = 12,
                            Name = "Siquirres"
                        },
                        new
                        {
                            DistrictId = 25,
                            CantonId = 13,
                            Name = "Liberia"
                        },
                        new
                        {
                            DistrictId = 26,
                            CantonId = 13,
                            Name = "Santa Cruz"
                        },
                        new
                        {
                            DistrictId = 27,
                            CantonId = 14,
                            Name = "Nicoya"
                        },
                        new
                        {
                            DistrictId = 28,
                            CantonId = 14,
                            Name = "Santa Cruz"
                        });
                });

            modelBuilder.Entity("API.Models.Inscription", b =>
                {
                    b.Property<int>("InscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InscriptionId"));

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<int>("VeterinarianId")
                        .HasColumnType("int");

                    b.HasKey("InscriptionId");

                    b.HasIndex("ClinicId");

                    b.HasIndex("VeterinarianId");

                    b.ToTable("Inscriptions");
                });

            modelBuilder.Entity("API.Models.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceId");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            ProvinceId = 1,
                            Name = "San José"
                        },
                        new
                        {
                            ProvinceId = 2,
                            Name = "Alajuela"
                        },
                        new
                        {
                            ProvinceId = 3,
                            Name = "Cartago"
                        },
                        new
                        {
                            ProvinceId = 4,
                            Name = "Heredia"
                        },
                        new
                        {
                            ProvinceId = 5,
                            Name = "Puntarenas"
                        },
                        new
                        {
                            ProvinceId = 6,
                            Name = "Limón"
                        },
                        new
                        {
                            ProvinceId = 7,
                            Name = "Guanacaste"
                        });
                });

            modelBuilder.Entity("API.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Indications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InscriptionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipeId");

                    b.HasIndex("AnimalId");

                    b.HasIndex("InscriptionId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("API.Models.Sex", b =>
                {
                    b.Property<int>("SexId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SexId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SexId");

                    b.ToTable("Sexes");

                    b.HasData(
                        new
                        {
                            SexId = 1,
                            Name = "Hombre"
                        },
                        new
                        {
                            SexId = 2,
                            Name = "Mujer"
                        },
                        new
                        {
                            SexId = 3,
                            Name = "Otro"
                        });
                });

            modelBuilder.Entity("API.Models.Surgery", b =>
                {
                    b.Property<int>("SurgeryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurgeryId"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InscriptionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SurgeryId");

                    b.HasIndex("AnimalId");

                    b.HasIndex("InscriptionId");

                    b.ToTable("Surgeries");
                });

            modelBuilder.Entity("API.Models.TypeAnimal", b =>
                {
                    b.Property<int>("TypeAnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeAnimalId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeAnimalId");

                    b.ToTable("TypeAnimals");

                    b.HasData(
                        new
                        {
                            TypeAnimalId = 1,
                            TypeName = "Perro"
                        },
                        new
                        {
                            TypeAnimalId = 2,
                            TypeName = "Gato"
                        },
                        new
                        {
                            TypeAnimalId = 3,
                            TypeName = "Conejo"
                        },
                        new
                        {
                            TypeAnimalId = 4,
                            TypeName = "Ave"
                        },
                        new
                        {
                            TypeAnimalId = 5,
                            TypeName = "Cabra"
                        });
                });

            modelBuilder.Entity("API.Models.Vaccine", b =>
                {
                    b.Property<int>("VaccineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaccineId"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InscriptionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VaccineId");

                    b.HasIndex("AnimalId");

                    b.HasIndex("InscriptionId");

                    b.ToTable("Vaccines");
                });

            modelBuilder.Entity("API.Models.Veterinarian", b =>
                {
                    b.Property<int>("VeterinarianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VeterinarianId"));

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentificationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("SecondLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SexId")
                        .HasColumnType("int");

                    b.HasKey("VeterinarianId");

                    b.HasIndex("SexId");

                    b.ToTable("veterinarians");
                });

            modelBuilder.Entity("API.Models.Animal", b =>
                {
                    b.HasOne("API.Models.Customer", "customer")
                        .WithMany("Animals")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.TypeAnimal", "TypeAnimal")
                        .WithMany("Animals")
                        .HasForeignKey("TypeAnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeAnimal");

                    b.Navigation("customer");
                });

            modelBuilder.Entity("API.Models.Appointment", b =>
                {
                    b.HasOne("API.Models.Animal", "Animal")
                        .WithMany("Appointments")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Inscription", "Inscription")
                        .WithMany("Appointments")
                        .HasForeignKey("InscriptionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Animal");

                    b.Navigation("Inscription");
                });

            modelBuilder.Entity("API.Models.Canton", b =>
                {
                    b.HasOne("API.Models.Province", "Province")
                        .WithMany("Cantons")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("API.Models.Customer", b =>
                {
                    b.HasOne("API.Models.Sex", "Sex")
                        .WithMany("Customers")
                        .HasForeignKey("SexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sex");
                });

            modelBuilder.Entity("API.Models.Diagnostic", b =>
                {
                    b.HasOne("API.Models.Animal", "Animal")
                        .WithMany("Diagnostics")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Inscription", "Inscription")
                        .WithMany("Diagnostics")
                        .HasForeignKey("InscriptionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Animal");

                    b.Navigation("Inscription");
                });

            modelBuilder.Entity("API.Models.Direction", b =>
                {
                    b.HasOne("API.Models.Clinic", "Clinic")
                        .WithMany("Directions")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("API.Models.District", "District")
                        .WithMany("Directions")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Customer");

                    b.Navigation("District");
                });

            modelBuilder.Entity("API.Models.District", b =>
                {
                    b.HasOne("API.Models.Canton", "Canton")
                        .WithMany("Districts")
                        .HasForeignKey("CantonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canton");
                });

            modelBuilder.Entity("API.Models.Inscription", b =>
                {
                    b.HasOne("API.Models.Clinic", "Clinic")
                        .WithMany("inscriptions")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Veterinarian", "Veterinarian")
                        .WithMany("Inscriptions")
                        .HasForeignKey("VeterinarianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Veterinarian");
                });

            modelBuilder.Entity("API.Models.Recipe", b =>
                {
                    b.HasOne("API.Models.Animal", "Animal")
                        .WithMany("Recipes")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Inscription", "Inscription")
                        .WithMany("Recipes")
                        .HasForeignKey("InscriptionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Animal");

                    b.Navigation("Inscription");
                });

            modelBuilder.Entity("API.Models.Surgery", b =>
                {
                    b.HasOne("API.Models.Animal", "Animal")
                        .WithMany("Surgeries")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Inscription", "Inscription")
                        .WithMany("Surgeries")
                        .HasForeignKey("InscriptionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Animal");

                    b.Navigation("Inscription");
                });

            modelBuilder.Entity("API.Models.Vaccine", b =>
                {
                    b.HasOne("API.Models.Animal", "Animal")
                        .WithMany("Vaccines")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Inscription", "Inscription")
                        .WithMany("Vaccines")
                        .HasForeignKey("InscriptionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Animal");

                    b.Navigation("Inscription");
                });

            modelBuilder.Entity("API.Models.Veterinarian", b =>
                {
                    b.HasOne("API.Models.Sex", "Sex")
                        .WithMany("Veterinarians")
                        .HasForeignKey("SexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sex");
                });

            modelBuilder.Entity("API.Models.Animal", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Diagnostics");

                    b.Navigation("Recipes");

                    b.Navigation("Surgeries");

                    b.Navigation("Vaccines");
                });

            modelBuilder.Entity("API.Models.Canton", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("API.Models.Clinic", b =>
                {
                    b.Navigation("Directions");

                    b.Navigation("inscriptions");
                });

            modelBuilder.Entity("API.Models.Customer", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("API.Models.District", b =>
                {
                    b.Navigation("Directions");
                });

            modelBuilder.Entity("API.Models.Inscription", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Diagnostics");

                    b.Navigation("Recipes");

                    b.Navigation("Surgeries");

                    b.Navigation("Vaccines");
                });

            modelBuilder.Entity("API.Models.Province", b =>
                {
                    b.Navigation("Cantons");
                });

            modelBuilder.Entity("API.Models.Sex", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Veterinarians");
                });

            modelBuilder.Entity("API.Models.TypeAnimal", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("API.Models.Veterinarian", b =>
                {
                    b.Navigation("Inscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
