# Utiliza la imagen oficial de Microsoft SQL Server desde Docker Hub
FROM mcr.microsoft.com/mssql/server

# Copia los scripts y archivos necesarios al contenedor
COPY ./Create_database.sql .
COPY ./start.sh .
COPY ./entrypoint.sh .

# Configura las variables de entorno para aceptar la licencia y establecer la contraseña del usuario 'sa'
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=Your!Passw0rd

# Cambia los permisos de ejecución para los scripts
RUN chown root:root ./start.sh && chmod +x ./start.sh

# Comando por defecto para ejecutar el script de entrada (entrypoint.sh)
CMD /bin/bash ./entrypoint.sh
